pcopr_srpm-kernel_rawhide: don't fail on kernel-headers builds
Building the kernel-headers package appears to be very fragile in
Rawhide, so don't treat failures here as fatal.

diff --git a/pcopr_srpm-kernel_rawhide b/pcopr_srpm-kernel_rawhide
--- a/pcopr_srpm-kernel_rawhide
+++ b/pcopr_srpm-kernel_rawhide
@@ -444,11 +444,14 @@ fedpkg prep || exit_error
 # build the kernel-headers source tarball
 notice "BUILDING THE HEADERS SOURCE TARBALL"
 fedpkg clone -a kernel-headers || exit_error
-./scripts/create_headers_tarball.sh || exit_error
-if [[ "$(specfile_version_changelog kernel.spec)" == "$(specfile_version_changelog kernel-headers/kernel-headers.spec)" ]]; then
-	(cd ./kernel-headers; fedpkg srpm) || exit_error
+if ./scripts/create_headers_tarball.sh; then
+	if [[ "$(specfile_version_changelog kernel.spec)" == "$(specfile_version_changelog kernel-headers/kernel-headers.spec)" ]]; then
+		(cd ./kernel-headers; fedpkg srpm) || exit_error
+	else
+		warn "kernel-headers revision mismatch, skipping"
+	fi
 else
-	warn "kernel-headers revision mismatch, skipping"
+	warn "kernel-headers build failure, skipping"
 fi
 
 # build srpm
