pcopr_srpm-kernel_rawhide: fix patch application and restore the prep stage
Credit to Ondrej Mosnacek for noticing that the patches were no
longer being applied in the SRPM.

diff --git a/pcopr_srpm-kernel_rawhide b/pcopr_srpm-kernel_rawhide
--- a/pcopr_srpm-kernel_rawhide
+++ b/pcopr_srpm-kernel_rawhide
@@ -413,6 +413,7 @@ fi
 # generate specfile patch snippet (if patches are present)
 notice "GENERATE SPECFILE PATCH REFERENCES"
 if [[ -n $(ls $dir_cwd/$DIR_PATCHES/*.patch 2> /dev/null) ]]; then
+	# definitions
 	echo "# START OF COPR PATCHES" > copr-patches.inc
 	for i in *-COPR-*.patch; do
 		echo $(basename $i) | \
@@ -421,6 +422,14 @@ if [[ -n $(ls $dir_cwd/$DIR_PATCHES/*.patch 2> /dev/null) ]]; then
 	echo "# END OF COPR PATCHES" >> copr-patches.inc
 	echo "" >> copr-patches.inc
 	cat copr-patches.inc
+	# application
+	echo "# START OF COPR PATCHES" > copr-patches-apply.inc
+	for i in *-COPR-*.patch; do
+		echo $(basename $i) | \
+			echo "ApplyPatch $i" >> copr-patches-apply.inc || exit_error
+	done
+	echo "# END OF COPR PATCHES" >> copr-patches-apply.inc
+	echo "" >> copr-patches-apply.inc
 fi
 
 # generate specfile changelog snippet
@@ -436,6 +445,7 @@ cp kernel.spec kernel.spec.orig
 notice "PATCH KERNEL SPECFILE"
 sed -i -e 's/^# define buildid .local/%define buildid .'$opt_revision'.'$PKG_VARIANT'/' kernel.spec || exit_error
 sed -n -i -e '/^# END OF PATCH DEFINITIONS/r copr-patches.inc' -e 1x -e '2,${x;p}' -e '${x;p}' kernel.spec || exit_error
+sed -n -i -e '/^# END OF PATCH APPLICATIONS/r copr-patches-apply.inc' -e 1x -e '2,${x;p}' -e '${x;p}' kernel.spec || exit_error
 
 # make a note in the changelog
 sed -i -e '/^%changelog/ r copr-changelog.inc' kernel.spec || exit_error
@@ -456,7 +466,7 @@ git diff kernel.spec
 # rpm prep stage
 notice "TEST KERNEL RPM PREP STAGE"
 # FIXME: temporary skipping due to kernel specfile problems
-#fedpkg prep || exit_error
+fedpkg prep || exit_error
 
 # if we are just doing a test run then exit here
 [[ $opt_test -eq 1 ]] && exit 0
